version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
    environment:
      - spring.data.mongodb.uri=mongodb://admin:admin@ds117070.mlab.com:17070/life-manager-dev
    