version: '3'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: 'sfg_dev'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sfg_dev_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'guru'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - '8080:8080'
    environment:
      - spring.data.mongodb.uri=mongodb://admin:admin@ds117070.mlab.com:17070/life-manager-dev
      - spring.profiles.active=dev
    